### PR TITLE
Wavetable xchange 6 mk

### PR DESCRIPTION
**Pull request by friedolino78**

### CODE REVIEW

**Review by JohannesLorenz — APPROVED** [review]
Code looks good :+1:

**Comment by JohannesLorenz** [comment]
Just one question: Can you hear a difference between lin and log? I personally do not hear it, or only hear it very slightly.

From the code (Envelope.cpp), there's a comment saying that the first point is always done linearly. But I also don't hear it well for the second point. At least, not for square wave.

**Comment by friedolino78** [comment]
> Just one question: Can you hear a difference between lin and log? I personally do not hear it, or only hear it very slightly.
> 
> From the code (Envelope.cpp), there's a comment saying that the first point is always done linearly. But I also don't hear it well for the second point. At least, not for square wave.

I didn't hear a difference neither. but i didn't look into the lin log calculation deep enough to have expectations about how it should sound..

**Comment by JohannesLorenz** [comment]
I forgot to merge this, doing it now...

**Pull request merged**
